// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/About.tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/device/computer.tsx";
import * as $4 from "./routes/device/network_device.tsx";
import * as $5 from "./routes/device/office_equipment.tsx";
import * as $6 from "./routes/device/server.tsx";
import * as $7 from "./routes/device/summary.tsx";
import * as $8 from "./routes/device/usb_key.tsx";
import * as $9 from "./routes/home.tsx";
import * as $10 from "./routes/index.tsx";
import * as $11 from "./routes/message.tsx";
import * as $12 from "./routes/network/ip_address.tsx";
import * as $13 from "./routes/network/network_type.tsx";
import * as $14 from "./routes/network/summary.tsx";
import * as $15 from "./routes/network/tel.tsx";
import * as $16 from "./routes/profile/document.tsx";
import * as $17 from "./routes/profile/index.tsx";
import * as $18 from "./routes/profile/topology.tsx";
import * as $19 from "./routes/user/account.tsx";
import * as $20 from "./routes/user/department.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LeftAside.tsx";
import * as $$2 from "./islands/RouteMenu.tsx";
import * as $$3 from "./islands/Table.tsx";
import * as $$4 from "./islands/TableBody.tsx";
import * as $$5 from "./islands/TableColumn.tsx";
import * as $$6 from "./islands/TableHeader.tsx";
import * as $$7 from "./islands/TableToolbar.tsx";

const manifest = {
  routes: {
    "./routes/About.tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/device/computer.tsx": $3,
    "./routes/device/network_device.tsx": $4,
    "./routes/device/office_equipment.tsx": $5,
    "./routes/device/server.tsx": $6,
    "./routes/device/summary.tsx": $7,
    "./routes/device/usb_key.tsx": $8,
    "./routes/home.tsx": $9,
    "./routes/index.tsx": $10,
    "./routes/message.tsx": $11,
    "./routes/network/ip_address.tsx": $12,
    "./routes/network/network_type.tsx": $13,
    "./routes/network/summary.tsx": $14,
    "./routes/network/tel.tsx": $15,
    "./routes/profile/document.tsx": $16,
    "./routes/profile/index.tsx": $17,
    "./routes/profile/topology.tsx": $18,
    "./routes/user/account.tsx": $19,
    "./routes/user/department.tsx": $20,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LeftAside.tsx": $$1,
    "./islands/RouteMenu.tsx": $$2,
    "./islands/Table.tsx": $$3,
    "./islands/TableBody.tsx": $$4,
    "./islands/TableColumn.tsx": $$5,
    "./islands/TableHeader.tsx": $$6,
    "./islands/TableToolbar.tsx": $$7,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
